apiVersion: batch/v1
kind: CronJob
metadata:
  name: clearsessions
spec:
  schedule: "0 0 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: k8s-django
            image: multipassport/k8s:latest
            imagePullPolicy: IfNotPresent
            command:
            - python
            - ./manage.py
            - clearsessions
          restartPolicy: Never