apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 60
  template:
    spec:
      containers:
      - name: k8s-django
        image: multipassport/k8s:latest
        command:
        - python
        - ./manage.py
        - migrate
        - --no-input
      restartPolicy: Never